language: node_js
node_js: 
  - "0.10"
addons:
  sauce_connect:
    username: "davisp1"
    access_key: "a151e8a4-3829-4875-b8b0-c6fcd35f3b5e"
before_script:
  - node_modules/ionic/bin/ionic serve &
  - node_modules/gulp/bin/gulp.js sass
script:
  - node_modules/gulp/bin/gulp.js e2e_sauce
env:
  - BACKEND=mocked
